---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[example2::default]
    attributes: {
      example2: {
        ntp_servers: [
          '0.pool.ntp.org',
          '1.pool.ntp.org',
          '2.pool.ntp.org',
          '3.pool.ntp.org'
        ]
      }
    }
