---
driver:
  name: vagrant

provisioner:
  name: chef_solo

sudo: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[example1::default]
    attributes: {}
