---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.0
    driver:
      customize:
        memory: 1024
    run_list:
      - recipe[yum-epel]

suites:
  - name: default
    run_list:
      - recipe[example4::default]
    attributes: {}
